-- quest 27123
DELETE FROM `creature` WHERE `guid` = '153134';
DELETE FROM `npc_spellclick_spells` WHERE `npc_entry` = '45005';
DELETE FROM `npc_spellclick_spells` WHERE `npc_entry` = '45042';
DELETE FROM `smart_scripts` WHERE `entryorguid` = '45005';
DELETE FROM `smart_scripts` WHERE `entryorguid` = '45042';

UPDATE `creature_template` SET `entry`='45005',  `npcflag`='0', `unit_class`='1', `unit_flags`='0', `unit_flags2`='2048', `dynamicflags`='0', `family`='0', `trainer_type`='0', `trainer_class`='0', `type`='1', `type_flags`='0', `type_flags2`='0', `spell1`='0', `spell2`='0', `spell3`='0', `spell4`='0', `spell5`='0', `spell6`='0', `spell7`='0', `spell8`='0', `AIName`='', `MovementType`='1', `InhabitType`='7', `questItem6`='0', `movementId`='0', `mechanic_immune_mask`='0', `flags_extra`='0', `ScriptName`='npc_deepholm_wyvern' WHERE (`entry`='45005');
UPDATE `creature_template` SET `entry`='45006',  `npcflag`='0', `unit_class`='2', `unit_flags`='0', `unit_flags2`='2048', `dynamicflags`='0', `family`='0', `trainer_type`='0', `trainer_class`='0', `type`='7', `type_flags`='0', `type_flags2`='0', `spell1`='0', `spell2`='0', `spell3`='0', `spell4`='0', `spell5`='0', `spell6`='0', `spell7`='0', `spell8`='0', `AIName`='', `MovementType`='0', `InhabitType`='3', `questItem6`='0', `movementId`='0', `mechanic_immune_mask`='0', `flags_extra`='0', `ScriptName`='npc_maelstorm_aggra' WHERE (`entry`='45006');
UPDATE `creature_template` SET `entry`='45024',  `npcflag`='0', `unit_class`='1', `unit_flags`='8', `unit_flags2`='2048', `dynamicflags`='0', `family`='0', `trainer_type`='0', `trainer_class`='0', `type`='1', `type_flags`='0', `type_flags2`='0', `spell1`='0', `spell2`='0', `spell3`='0', `spell4`='0', `spell5`='0', `spell6`='0', `spell7`='0', `spell8`='0', `AIName`='', `MovementType`='0', `InhabitType`='3', `questItem6`='0', `movementId`='199', `mechanic_immune_mask`='0', `flags_extra`='0', `ScriptName`='npc_deepholm_wyvern_ride' WHERE (`entry`='45024');
UPDATE `creature_template` SET `entry`='45042',  `npcflag`='2', `unit_class`='2', `unit_flags`='33536', `unit_flags2`='34816', `dynamicflags`='0', `family`='0', `trainer_type`='0', `type`='7', `type_flags`='4', `type_flags2`='0', `spell1`='0', `spell2`='0', `spell3`='0', `spell4`='0', `spell5`='0', `spell6`='0', `spell7`='0', `spell8`='0', `VehicleId`='0', `AIName`='', `MovementType`='0', `InhabitType`='3', `questItem6`='0', `movementId`='0', `mechanic_immune_mask`='617299967', `flags_extra`='0', `ScriptName`='' WHERE (`entry`='45042');

INSERT INTO `creature_text` (`entry`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `comment`) VALUES ('45006', '0', '0', 'I hope you have a strong stomach.  Travelling through the breach is not for the weak.', '12', '0', '100', '0', '0', '22606', '45169', '0');
INSERT INTO `creature_text` (`entry`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `comment`) VALUES ('45006', '1', '0', 'We\'re at the center of the Maelstrom, the rift between Deepholm and Azeroth.  Watch as it threatens to tear your world apart!', '12', '0', '100', '0', '0', '22607', '45170', '0');
INSERT INTO `creature_text` (`entry`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `comment`) VALUES ('45006', '2', '0', 'Let us hope Thrall and the others can contain it while you\'re inside.', '12', '0', '100', '0', '0', '22608', '45171', '0');
INSERT INTO `creature_text` (`entry`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `comment`) VALUES ('45006', '3', '0', 'This is it!  Brace yourself!', '14', '0', '100', '0', '0', '22609', '45172', '0');
INSERT INTO `creature_text` (`entry`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `comment`) VALUES ('45006', '4', '0', 'You made it!  Good!', '12', '0', '100', '4', '0', '22610', '45175', '0');
INSERT INTO `creature_text` (`entry`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `comment`) VALUES ('45006', '5', '0', 'This is the Temple of Earth.  It\'s the most important structure in Deepholm.', '12', '0', '100', '0', '0', '22611', '45176', '0');
INSERT INTO `creature_text` (`entry`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `comment`) VALUES ('45006', '6', '0', 'There was once a Titan-made stone inside.  It was known as the World Pillar.  The name was literal.  It bore the weight of all the elemental and magnetic forces in Deepholm.', '12', '0', '100', '0', '0', '22612', '45180', '0');
INSERT INTO `creature_text` (`entry`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `comment`) VALUES ('45006', '7', '0', 'It was shattered when Deathwing broke through the dome above and created the rift between the two worlds.  All of Deepholm is going to collapse into Azeroth if we do not put the World Pillar back together.', '12', '0', '100', '0', '0', '22613', '45182', '0');
INSERT INTO `creature_text` (`entry`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `comment`) VALUES ('45006', '8', '0', 'The first fragment was going to be delivered to us by a Horde gunship known as the Storm\'s Fury.  It never made it here.', '12', '0', '100', '0', '0', '22614', '45186', '0');
INSERT INTO `creature_text` (`entry`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `comment`) VALUES ('45006', '9', '0', 'We\'ve taken control of the temple and we\'re containing as much of the damage as we can.  Go inside and speak to Maruut; he\'s in charge.', '12', '0', '100', '0', '0', '22615', '45187', '0');
INSERT INTO `creature_text` (`entry`, `GroupID`, `ID`, `Text`, `Type`, `Language`, `Probability`, `Emote`, `Duration`, `Sound`, `BroadcastTextId`, `comment`) VALUES ('45006', '10', '0', 'We are all counting on you.', '12', '0', '100', '0', '0', '22616', '45191', '0');

UPDATE `spell_target_position` SET `id`='84073', `target_map`='646', `target_position_x`='993.12', `target_position_y`='521.531', `target_position_z`='-49.3349', `target_orientation`='0' WHERE (`id`='84073');
UPDATE `quest_template` SET `Flags`='8' WHERE (`Id`='27203')