insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','76456','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','76457','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','76458','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','76459','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','76461','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','76462','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','76463','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','76464','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','76465','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','76466','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','76467','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','76468','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','76469','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','76470','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','76471','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','76472','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78444','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78446','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78447','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78448','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78449','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78450','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78451','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78452','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78453','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78454','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78455','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78456','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78457','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78458','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78459','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78468','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78469','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78470','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78471','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78473','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78474','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78479','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78481','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78482','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78483','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78484','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78485','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','78486','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99439','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99440','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99441','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99443','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99445','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99446','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99447','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99452','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99453','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99454','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99455','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99456','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99457','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99458','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99539','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99540','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99541','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99542','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99543','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99544','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99660','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','101924','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','101925','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','101928','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','101929','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','101931','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','101932','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','101933','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','101934','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','101935','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','101936','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','101937','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','101939','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','101940','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','101941','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','75306','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','75291','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','101921','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','75304','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','75292','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','75305','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','75303','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','101920','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','75307','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','75302','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','75297','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99460','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99459','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','75294','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','101923','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','101922','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','75270','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','75290','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','75296','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99448','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99449','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','75295','3','','','DISABLE PROFFESION SPELLS');
insert into `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('0','99537','3','','','DISABLE PROFFESION SPELLS');
/*
SQLyog Community v13.1.7 (64 bit)
MySQL - 5.7.42-log 
*********************************************************************
*/
/*!40101 SET NAMES utf8 */;

  DELETE FROM `npc_trainer` WHERE `spell`= 76456;
  DELETE FROM `npc_trainer` WHERE `spell`= 76457; 
  DELETE FROM `npc_trainer` WHERE `spell`= 76458;
  DELETE FROM `npc_trainer` WHERE `spell`= 76459;  
  DELETE FROM `npc_trainer` WHERE `spell`= 76461;  
  DELETE FROM `npc_trainer` WHERE `spell`= 76462;  
  DELETE FROM `npc_trainer` WHERE `spell`= 76463;  
  DELETE FROM `npc_trainer` WHERE `spell`= 76464;  
  DELETE FROM `npc_trainer` WHERE `spell`= 76465;  
  DELETE FROM `npc_trainer` WHERE `spell`= 76466;  
  DELETE FROM `npc_trainer` WHERE `spell`= 76467;  
  DELETE FROM `npc_trainer` WHERE `spell`= 76468;  
  DELETE FROM `npc_trainer` WHERE `spell`= 76469;  
  DELETE FROM `npc_trainer` WHERE `spell`= 76470;  
  DELETE FROM `npc_trainer` WHERE `spell`= 76471;  
  DELETE FROM `npc_trainer` WHERE `spell`= 76472;  
  DELETE FROM `npc_trainer` WHERE `spell`= 78444;  
  DELETE FROM `npc_trainer` WHERE `spell`= 78446;  
  DELETE FROM `npc_trainer` WHERE `spell`= 78447;  
  DELETE FROM `npc_trainer` WHERE `spell`= 78448;  
  DELETE FROM `npc_trainer` WHERE `spell`= 78449;  
  DELETE FROM `npc_trainer` WHERE `spell`= 78450; 
  DELETE FROM `npc_trainer` WHERE `spell`= 78451; 
  DELETE FROM `npc_trainer` WHERE `spell`= 78452; 
  DELETE FROM `npc_trainer` WHERE `spell`= 78453; 
  DELETE FROM `npc_trainer` WHERE `spell`= 78454; 
  DELETE FROM `npc_trainer` WHERE `spell`= 78455; 
  DELETE FROM `npc_trainer` WHERE `spell`= 78456; 
  DELETE FROM `npc_trainer` WHERE `spell`= 78457; 
  DELETE FROM `npc_trainer` WHERE `spell`= 78458; 
  DELETE FROM `npc_trainer` WHERE `spell`= 78459; 
  DELETE FROM `npc_trainer` WHERE `spell`= 78468; 
  DELETE FROM `npc_trainer` WHERE `spell`= 78469; 
  DELETE FROM `npc_trainer` WHERE `spell`= 78470; 
  DELETE FROM `npc_trainer` WHERE `spell`= 78471; 
  DELETE FROM `npc_trainer` WHERE `spell`= 78473; 
  DELETE FROM `npc_trainer` WHERE `spell`= 78474; 
  DELETE FROM `npc_trainer` WHERE `spell`= 78479; 
  DELETE FROM `npc_trainer` WHERE `spell`= 78481; 
  DELETE FROM `npc_trainer` WHERE `spell`= 78482; 
  DELETE FROM `npc_trainer` WHERE `spell`= 78483; 
  DELETE FROM `npc_trainer` WHERE `spell`= 78484; 
  DELETE FROM `npc_trainer` WHERE `spell`= 78485; 
  DELETE FROM `npc_trainer` WHERE `spell`= 78486; 
  DELETE FROM `npc_trainer` WHERE `spell`= 99439; 
  DELETE FROM `npc_trainer` WHERE `spell`= 99440; 
  DELETE FROM `npc_trainer` WHERE `spell`= 99441; 
  DELETE FROM `npc_trainer` WHERE `spell`= 99443; 
  DELETE FROM `npc_trainer` WHERE `spell`= 99445; 
  DELETE FROM `npc_trainer` WHERE `spell`= 99446; 
  DELETE FROM `npc_trainer` WHERE `spell`= 99447; 
  DELETE FROM `npc_trainer` WHERE `spell`= 99452; 
  DELETE FROM `npc_trainer` WHERE `spell`= 99453; 
  DELETE FROM `npc_trainer` WHERE `spell`= 99454; 
  DELETE FROM `npc_trainer` WHERE `spell`= 99455; 
  DELETE FROM `npc_trainer` WHERE `spell`= 99456; 
  DELETE FROM `npc_trainer` WHERE `spell`= 99457; 
  DELETE FROM `npc_trainer` WHERE `spell`= 99458; 
  DELETE FROM `npc_trainer` WHERE `spell`= 99539; 
  DELETE FROM `npc_trainer` WHERE `spell`= 99540; 
  DELETE FROM `npc_trainer` WHERE `spell`= 99541; 
  DELETE FROM `npc_trainer` WHERE `spell`= 99542; 
  DELETE FROM `npc_trainer` WHERE `spell`= 99543; 
  DELETE FROM `npc_trainer` WHERE `spell`= 99544; 
  DELETE FROM `npc_trainer` WHERE `spell`= 99660; 
  DELETE FROM `npc_trainer` WHERE `spell`= 101924;  
  DELETE FROM `npc_trainer` WHERE `spell`= 101925; 
  DELETE FROM `npc_trainer` WHERE `spell`= 101928; 
  DELETE FROM `npc_trainer` WHERE `spell`= 101929; 
  DELETE FROM `npc_trainer` WHERE `spell`= 101931; 
  DELETE FROM `npc_trainer` WHERE `spell`= 101932; 
  DELETE FROM `npc_trainer` WHERE `spell`= 101933; 
  DELETE FROM `npc_trainer` WHERE `spell`= 101934; 
  DELETE FROM `npc_trainer` WHERE `spell`= 101935; 
  DELETE FROM `npc_trainer` WHERE `spell`= 101936; 
  DELETE FROM `npc_trainer` WHERE `spell`= 101937; 
  DELETE FROM `npc_trainer` WHERE `spell`= 101939; 
  DELETE FROM `npc_trainer` WHERE `spell`= 101940; 
  DELETE FROM `npc_trainer` WHERE `spell`= 101941; 
  DELETE FROM `npc_trainer` WHERE `spell`= 75306;
  DELETE FROM `npc_trainer` WHERE `spell`= 75291; 
  DELETE FROM `npc_trainer` WHERE `spell`= 101921;  
  DELETE FROM `npc_trainer` WHERE `spell`= 75304;  
  DELETE FROM `npc_trainer` WHERE `spell`= 75292;  
  DELETE FROM `npc_trainer` WHERE `spell`= 75305;  
  DELETE FROM `npc_trainer` WHERE `spell`= 75303;  
  DELETE FROM `npc_trainer` WHERE `spell`= 101920;  
  DELETE FROM `npc_trainer` WHERE `spell`= 75307;  
  DELETE FROM `npc_trainer` WHERE `spell`= 75302;  
  DELETE FROM `npc_trainer` WHERE `spell`= 75297;  
  DELETE FROM `npc_trainer` WHERE `spell`= 99460;  
  DELETE FROM `npc_trainer` WHERE `spell`= 99459;  
  DELETE FROM `npc_trainer` WHERE `spell`= 75294;  
  DELETE FROM `npc_trainer` WHERE `spell`= 101923;  
  DELETE FROM `npc_trainer` WHERE `spell`= 101922;  
  DELETE FROM `npc_trainer` WHERE `spell`= 75270;  
  DELETE FROM `npc_trainer` WHERE `spell`= 75290;  
  DELETE FROM `npc_trainer` WHERE `spell`= 75296;  
  DELETE FROM `npc_trainer` WHERE `spell`= 99448;  
  DELETE FROM `npc_trainer` WHERE `spell`= 99449;  
  DELETE FROM `npc_trainer` WHERE `spell`= 75295;  
  DELETE FROM `npc_trainer` WHERE `spell`= 99537;  
