REPLACE INTO `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('2','724','15','','','Disable Ruby Sanctum');
REPLACE INTO `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('2','603','15','','','Disable Ulduar');
REPLACE INTO `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('2','938','15','','','Disable Fin de los Dias');
REPLACE INTO `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('2','859','15','','','Disable Zul Gurub');
REPLACE INTO `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('2','940','15','','','Disable La Hora del Crepúsculo');
REPLACE INTO `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('2','939','15','','','Disble Pozo de la Eternidad');
REPLACE INTO `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('2','967','15','','','Disable Alma de Dragón');
REPLACE INTO `disables` (`sourceType`, `entry`, `flags`, `params_0`, `params_1`, `comment`) values('2','720','15','','','Disable Tierras de Fuego');
DELETE FROM `npc_vendor` WHERE `item`= 67093;
DELETE FROM `npc_vendor` WHERE `item`= 67091;
DELETE FROM `npc_vendor` WHERE `item`= 67080;
DELETE FROM `npc_vendor` WHERE `item`= 67081;
DELETE FROM `npc_vendor` WHERE `item`= 67092;
DELETE FROM `npc_vendor` WHERE `item`= 67090;
DELETE FROM `npc_vendor` WHERE `item`= 67087;
DELETE FROM `npc_vendor` WHERE `item`= 67079;
DELETE FROM `npc_vendor` WHERE `item`= 67089;
DELETE FROM `npc_vendor` WHERE `item`= 67086;
DELETE FROM `npc_vendor` WHERE `item`= 67085;
DELETE FROM `npc_vendor` WHERE `item`= 67081;
DELETE FROM `npc_vendor` WHERE `item`= 67078;
DELETE FROM `npc_vendor` WHERE `item`= 67066;
DELETE FROM `npc_vendor` WHERE `item`= 67065;
DELETE FROM `npc_vendor` WHERE `item`= 67058;
DELETE FROM `npc_vendor` WHERE `item`= 67075;
DELETE FROM `npc_vendor` WHERE `item`= 67074;
DELETE FROM `npc_vendor` WHERE `item`= 67062;
DELETE FROM `npc_vendor` WHERE `item`= 67077;
DELETE FROM `npc_vendor` WHERE `item`= 67076;
DELETE FROM `npc_vendor` WHERE `item`= 67064;
DELETE FROM `npc_vendor` WHERE `item`= 67060;
DELETE FROM `npc_vendor` WHERE `item`= 67055;
DELETE FROM `npc_vendor` WHERE `item`= 67049;
DELETE FROM `npc_vendor` WHERE `item`= 67046;
DELETE FROM `npc_vendor` WHERE `item`= 67053;
DELETE FROM `npc_vendor` WHERE `item`= 67063;
DELETE FROM `npc_vendor` WHERE `item`= 67048;
DELETE FROM `npc_vendor` WHERE `item`= 67042;
DELETE FROM `npc_vendor` WHERE `item`= 67056;
DELETE FROM `npc_vendor` WHERE `item`= 67054;
DELETE FROM `npc_vendor` WHERE `item`= 67044;
DELETE FROM `npc_vendor` WHERE `item`= 66128;
DELETE FROM `npc_vendor` WHERE `item`= 66124;
DELETE FROM `npc_vendor` WHERE `item`= 66127;
DELETE FROM `npc_vendor` WHERE `item`= 66122;
DELETE FROM `npc_vendor` WHERE `item`= 66126;
DELETE FROM `npc_vendor` WHERE `item`= 66125;
DELETE FROM `npc_vendor` WHERE `item`= 66118;
DELETE FROM `npc_vendor` WHERE `item`= 66132;
DELETE FROM `npc_vendor` WHERE `item`= 66123;
DELETE FROM `npc_vendor` WHERE `item`= 66117;
DELETE FROM `npc_vendor` WHERE `item`= 66120;
DELETE FROM `npc_vendor` WHERE `item`= 66130;
DELETE FROM `npc_vendor` WHERE `item`= 66121;
DELETE FROM `npc_vendor` WHERE `item`= 66129;
DELETE FROM `npc_vendor` WHERE `item`= 66119;
DELETE FROM `npc_vendor` WHERE `item`= 66131;
DELETE FROM `npc_vendor` WHERE `item`= 54598;
DELETE FROM `npc_vendor` WHERE `item`= 54595;
DELETE FROM `npc_vendor` WHERE `item`= 54593;
DELETE FROM `npc_vendor` WHERE `item`= 54594;
DELETE FROM `npc_vendor` WHERE `item`= 54597;
DELETE FROM `npc_vendor` WHERE `item`= 54596;


