/* Eliminando errores en la carga de la bD */

DELETE FROM `npc_vendor` WHERE `entry`=500026;
DELETE FROM `npc_vendor` WHERE `entry`=500027;
DELETE FROM `npc_vendor` WHERE `entry`=500111;
DELETE FROM `npc_vendor` WHERE `entry`=500046;
DELETE FROM `npc_vendor` WHERE `entry`=500057;
DELETE FROM `npc_vendor` WHERE `entry`=500113;
DELETE FROM `npc_vendor` WHERE `entry`=500068;
DELETE FROM `npc_vendor` WHERE `entry`=500095;
DELETE FROM `npc_vendor` WHERE `entry`=500097;
DELETE FROM `npc_vendor` WHERE `entry`=500110;
DELETE FROM `npc_vendor` WHERE `entry`=999962;

INSERT INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (6984, 2);
INSERT INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29371, 12);
INSERT INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES(13952, 51);
INSERT INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES(14166, 51);
INSERT INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES(14167, 51);
INSERT INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES(14168, 51);
INSERT INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES(14169, 51);
INSERT INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES(14170, 51);
INSERT INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES(14171, 51);
INSERT INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES(14172, 51);
INSERT INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES(14174, 51);
INSERT INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES(14175, 51);
INSERT INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES(14176, 51);
INSERT INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES(14177, 51);
INSERT INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES(27841, 51);
INSERT INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES(27846, 51);

REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28934, 8);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28935, 8);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29054, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29396, 24);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29397, 24);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29374, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29144, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29375, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29377, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29075, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29376, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29430, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29431, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29734, 7);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29735, 7);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29736, 7);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29737, 7);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29738, 7);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29739, 7);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29740, 7);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29741, 7);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29742, 7);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (14022, 26);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29000, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29007, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29005, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29001, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29002, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29003, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29004, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29006, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29074, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29385, 52);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28912, 1);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28915, 1);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28916, 1);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28917, 1);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28918, 1);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28919, 1);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28920, 1);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28921, 1);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28951, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28952, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28953, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28958, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28989, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28954, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28956, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28960, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28961, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28963, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28964, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28968, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28970, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28977, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28980, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28978, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28979, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28985, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28983, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28988, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28991, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28990, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28955, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28965, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28967, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28992, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28981, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28982, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28957, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28959, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28962, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28966, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28969, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28971, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28972, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28973, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28974, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28975, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28976, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28984, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28986, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28987, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28993, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28994, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28995, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28996, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28998, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (28999, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29000, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29001, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29002, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29003, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29004, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29005, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29006, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29007, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29008, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29009, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29010, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29011, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29012, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29013, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29014, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29016, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29017, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29018, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29019, 12);
REPLACE INTO `game_event_seasonal_questrelation` (`questId`, `eventEntry`) VALUES (29020, 12);
