/*npc textos ds*/ 
REPLACE INTO `locales_creature_text` (`entry`, `groupid`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`) values('57807','0','0','%s attempts to run away in fear!','%s essaie de s\'enfuir dans un moment de panique  !',NULL,NULL,NULL,'¡%s intenta huir con miedo!','¡%s intenta huir con miedo!',NULL);
REPLACE INTO `locales_creature_text` (`entry`, `groupid`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`) values('57807','1','0','You will be easy prey, $c.','Vous serez une proie facile, $C.',NULL,NULL,NULL,'Serás presa fácil, $c.','Serás presa fácil, $c.',NULL);
REPLACE INTO `locales_creature_text` (`entry`, `groupid`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`) values('57807','1','1','My Magic will shred your puny body, $r.','',NULL,NULL,NULL,'Mi magia destrozará tu cuerpo enclenque, $r.','Mi magia destrozará tu cuerpo enclenque, $r.',NULL);
REPLACE INTO `locales_creature_text` (`entry`, `groupid`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`) values('57807','1','2','A fine trophy your head will make, $r.','Votre tête fera un trophée parfait , $R.',NULL,NULL,NULL,'Un buen trofeo será tu cabeza, $r.','Un buen trofeo será tu cabeza, $r.',NULL);
REPLACE INTO `locales_creature_text` (`entry`, `groupid`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`) values('57817','0','0','%s attempts to run away in fear!','%s essaie de s\'enfuir dans un moment de panique  !',NULL,NULL,NULL,'%s attempts to run away in fear!','%s attempts to run away in fear!',NULL);
REPLACE INTO `locales_creature_text` (`entry`, `groupid`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`) values('57817','1','0','You will be easy prey, $c.','Vous serez une proie facile, $C.',NULL,NULL,NULL,'Serás presa fácil, $c.','Serás presa fácil, $c.',NULL);
REPLACE INTO `locales_creature_text` (`entry`, `groupid`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`) values('57817','1','1','My Magic will shred your puny body, $r.','',NULL,NULL,NULL,'Mi magia destrozará tu cuerpo enclenque, $r.','Mi magia destrozará tu cuerpo enclenque, $r.',NULL);
REPLACE INTO `locales_creature_text` (`entry`, `groupid`, `id`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`) values('57817','1','2','A fine trophy your head will make, $r.','Votre tête fera un trophée parfait , $R.',NULL,NULL,NULL,'Un buen trofeo será tu cabeza, $r.','Un buen trofeo será tu cabeza, $r.',NULL);
