/*dialogos Dr tratabien*/
REPLACE INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `comment`) values('39034','0','0','Todas las Damas y Caballeros presentes deben SALIR AHORA... ¡porque solo HOMBRES Y MUJERES DE VERDAD podrán manejar el espectáculo sangriento que está a punto de desarrollarse! Presentamos al primer luchador, el guerrero de Wastewander, el ayatolá de Kaja-Cola... ¡EL GINORMUS!','14','0','100','0','0','0','0','Dr. Tratabien Grita');
REPLACE INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `comment`) values('39034','1','0','¡El Ginormus ha caído! $N se parece a $g él: ¡ella; está lista para más!','14','0','100','0','0','0','0','Dr. Tratabien Grita a Ginormus Muerto');
REPLACE INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `comment`) values('39034','2','0','¡En el Thunderdrome, $N! No hay forma de salir hasta que alguien golpea la arena. ¡Comencemos el espectáculo!','12','0','100','0','0','0','0','Dr. Tratabien Dice Zumonga Entra');
REPLACE INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `comment`) values('39034','3','0','¡Nuestro próximo luchador fue encontrado en las tumbas más profundas de Zul\'Farrak! Atiborrado de sangre maldita, resucitado de la muerte innumerables veces, ¡ahora solo conoce la furia y la violencia! ¡Atrévete a enfrentar la ira sin sentido de... ZUMONGA!','14','0','100','0','0','0','39195','Dr. Tratabien Grita Zumonga Entra');
REPLACE INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `comment`) values('39034','4','0','¡$N lo ha vuelto a hacer! ¡Zumonga muere una vez más!','14','0','100','0','0','0','0','Dr. Tratabien grita muerte de Zumonga');
REPLACE INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `comment`) values('39034','5','0','¡Los débiles de corazón pueden desear protegerse los ojos! ¡Ser llevado al ring ahora es un horror capturado de los oscuros túneles de Centipaar Hive! Os doy la muerte resbaladiza: ¡SARINEXX!','14','0','100','0','0','0','0','Dr. Tratabien Grita Sarinexx Entra');
REPLACE INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `comment`) values('39034','6','0','¡No hay forma de parar $N! ¡Sarinexx ha sido masacrado!','14','0','100','0','0','0','0','Dr. Tratabien grita la muerte de Sarinexx');
REPLACE INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `comment`) values('39034','7','0','¡Y eso es todo, amigos! ¡Este conflicto se ha resuelto como se debe, con VIOLENCIA! ¡Vamos a escucharlo para nuestros concursantes!','14','0','100','0','0','0','0','Dr. Tratabien grita pelea de rencores completa');
