/* Condiciones para Gossip relacionado a quet 26337 */

REPLACE INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES (15, 11659, 0, 0, 0, 9, 0, 26337, 0, 0, 0, 0, 0, '');

/* Npc se mueven random, no deberia suceder */

UPDATE `creature` SET `MovementType`=0 WHERE `guid`=138856;
UPDATE `creature` SET `MovementType`=0 WHERE `guid`=142401;
UPDATE `creature` SET `MovementType`=0 WHERE `guid`=142400;
UPDATE `creature` SET `MovementType`=0 WHERE `guid`=138855;
UPDATE `creature` SET `MovementType`=0 WHERE `guid`=138854;

/* Smart teletransporta y completa la mision automaticamente, no deberia suceder */

DELETE FROM `smart_scripts` WHERE `entryorguid`=50367;

/* Textos Faltantes */

insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','0','0','Abordando la Lanza de Durotar, ¿verdad? ¡Eres digno de envidia, marine de la Horda!','12','0','100','1','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','1','0','Está a punto de abrir un nuevo agujero en el horizonte a bordo de una nueva era sensacional en la innovación aeronáutica.','12','0','100','273','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','2','0','Ha sido diseñado imprudentemente con un desprecio despiadado tanto por las preocupaciones presupuestarias como por las engorrosas e ineficientes \"leyes de la física\".','12','0','100','5','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','3','0','Mientras espera su llegada, mi asistente y yo demostraremos momentáneamente algunas de las características de este notable avión.','12','0','100','1','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','4','0','Como sabes, el aire no pesa nada. Entonces, para crear una embarcación más ligera que el aire, tuvimos que romper algunas reglas.','12','0','100','1','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','5','0','La Lanza de Durotar está llena hasta el punto de estallar con gas combustible sobrecalentado.','12','0','100','273','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','6','0','Los ingenieros de Bilgewater han aprovechado su inherente inestabilidad a gran altitud y el bajo costo resultante.','12','0','100','1','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','7','0','Hemos mitigado la inestabilidad explosiva del gas poniéndolo bajo una presión INMENSA.','12','0','100','1','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','8','0','Hacerlo requirió la eliminación de una serie de válvulas de seguridad que seguían estallando.','12','0','100','274','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','9','0','Dios mío, sí. Con el fin de maximizar tanto el alcance como la carga útil, hemos elaborado una mezcla poco ortodoxa de combustibles para cohetes para los motores de última generación.','12','0','100','25','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','10','0','Es tan denso en energía que se quema a la menor provocación.','12','0','100','273','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','11','0','Este material es tan volátil que probablemente no debería moverse. Mucho menos... volado.','12','0','100','274','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','12','0','Tu curso de hoy te llevará directamente a través del gran mar.','12','0','100','1','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','13','0','Una enorme e implacable extensión de fuertes olas grises, temperaturas bajo cero y una voraz vida marina.','12','0','100','274','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','14','0','Confía en mí, amigo, una muerte rápida inducida por una píldora es mucho mejor que el largo y agonizante proceso de hipotermia y posterior desmembramiento por parte de los tiburones.','12','0','100','1','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','15','0','No preguntes cómo sabemos a qué saben.','12','0','100','6','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','16','0','Si su zepelín es atacado en ruta, el pánico no es recomendable.','12','0','100','274','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','17','0','En su lugar, busque una serie de cañones antiaéreos montados en la cubierta posicionados para tal emergencia.','12','0','100','1','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','18','0','Greely, muéstrales cómo funcionan las armas.','12','0','100','25','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','19','0','Simplemente apunta y aprieta el gatillo. O no apuntes. Me lavo las manos de todo el asunto.','12','0','100','1','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','20','0','Greely, no estarás disparando al azar esa cosa al Puerto Pantoque, ¿verdad?','12','0','100','6','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','21','0','En el improbable caso de que una falla catastrófica no mate instantáneamente a todos a bordo...','12','0','100','1','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','22','0','...aparecerán varios paracaídas a lo largo de las barandillas.','12','0','100','273','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','23','0','Simplemente tome un paracaídas cercano para saltar lejos del zepelín en llamas. Con suerte en tierra firme.','12','0','100','1','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','24','0','Greely, ¿te gustaría demostrar cómo funcionan nuestros paracaídas?','12','0','100','6','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','25','0','Muy bien entonces. Veo que la Lanza de Durotar casi ha llegado.','12','0','100','1','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','26','0','Su seguridad y bienestar ya no son una preocupación mía.','12','0','100','274','0','0','Hobart Grapplehammer','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47209','27','0','¡Diviértete asaltando las Tierras Altas!','12','0','100','3','0','0','Hobart Grapplehammer','0');


insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47208','0','0','¡No se desperdició ni un centavo en comodidad o seguridad personal!','12','0','100','4','0','0','Assistant Greely','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47208','1','0','¡Doblamos la basura de ellos!','12','0','100','5','0','0','Assistant Greely','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47208','2','0','Nos pasamos los ahorros a nosotros.','12','0','100','273','0','0','Assistant Greely','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47208','3','0','Pregúntese: ¿de qué sirve una válvula de \"seguridad\" si se sigue disparando? Eso no suena muy seguro para mí.','12','0','100','6','0','0','Assistant Greely','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47208','4','0','Háblales de los motores, jefe.','12','0','100','273','0','0','Assistant Greely','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47208','5','0','Lo llamamos \"Cupula Jugosa\".','12','0','100','1','0','0','Assistant Greely','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47208','6','0','Incluso verbales.','12','0','100','273','0','0','Assistant Greely','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47208','7','0','Para garantizar una respuesta rápida de la tripulación en caso de incendio, el almacenamiento de combustible se alejó de los camarotes de la tripulación y se colocó debajo del compartimiento de pasajeros.','12','0','100','1','0','0','Assistant Greely','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47208','8','0','En el improbable caso de un \"aterrizaje\" en el agua, busque debajo del cojín de su asiento donde se ha colocado una cápsula de cianuro para su comodidad.','12','0','100','1','0','0','Assistant Greely','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47208','9','0','Para aquellos de ustedes alérgicos a las almendras, nuestras cápsulas de cianuro vienen en una variedad de sabores.','12','0','100','273','0','0','Assistant Greely','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47208','10','0','También encontrarás una bolsa de cacahuetes complementaria.','12','0','100','1','0','0','Assistant Greely','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47208','11','0','¡Nada mantiene más segura a una flota de dirigibles combustibles que arrojar metal fundido al azar en todas las direcciones imaginables!','12','0','100','4','0','0','Assistant Greely','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47208','12','0','¡Con mucho gusto!','12','0','100','273','0','0','Assistant Greely','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47208','13','0','¡Puedo golpear mi casa desde aquí!','12','0','100','5','0','0','Assistant Greely','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47208','14','0','No.','12','0','100','6','0','0','Assistant Greely','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47208','15','0','A lo mejor.','12','0','100','0','0','0','Assistant Greely','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47208','16','0','Un poco.','12','0','100','0','0','0','Assistant Greely','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47208','17','0','Los llamamos \"Dispositivos de desembarque sin rampa de emergencia\".','12','0','100','1','0','0','Assistant Greely','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47208','18','0','¡Oh demonios no! ¡Esas cosas son trampas mortales!','12','0','100','5','0','0','Assistant Greely','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47208','19','0','De parte de todos nosotros en el puerto de Aguas Estancadas...','12','0','100','1','0','0','Assistant Greely','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47208','20','0','¡Diviértete asaltando las Tierras Altas!','12','0','100','3','0','0','Assistant Greely','0');


insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47206','0','0','El Zeppelin llegará en seis minutos.','12','0','100','1','0','22491','Loudspeaker','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47206','1','0','El Zeppelin llegará encinco minutos.','12','0','100','1','0','22491','Loudspeaker','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47206','2','0','El Zeppelin llegará en cuatro minutos.','12','0','100','1','0','22491','Loudspeaker','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47206','3','0','El Zeppelin llegará en tres minutos.','12','0','100','1','0','22491','Loudspeaker','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47206','4','0','El Zeppelin llegará en dos minutos.','12','0','100','1','0','22491','Loudspeaker','0');
insert into `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `comment`, `BroadcastTextID`) values('47206','5','0','El Zeppelin llegará enun minuto. Un minuto.','12','0','100','1','0','22491','Loudspeaker','0');

/* Update smarts script for THis NPC */

UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=47209;
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=47208;
UPDATE `creature_template` SET `AIName`='SmartAI' WHERE `entry`=47206;
UPDATE `creature` SET `phaseMask`=8 WHERE id=47210;
UPDATE `creature` SET `phaseMask`=8 WHERE id=47217;

