DELETE FROM `smart_scripts` WHERE `entryorguid`=42646;

insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('42646','0','0','1','62','0','100','0','7','1','0','0','1','0','0','0','0','0','0','1','0','0','0','0','0','0','0','On gossip action 1 from menu 7 selected - Self: Talk 0 to invoker');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('42646','0','1','2','61','0','100','0','0','0','0','0','28','80109','0','0','0','0','0','1','0','0','0','0','0','0','0','On gossip action 1 from menu 7 selected - Self: Remove aura due to spell 80109');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('42646','0','2','0','61','0','100','0','0','0','0','0','2','16','0','0','0','0','0','1','0','0','0','0','0','0','0','On gossip action 1 from menu 7 selected - Self: Set faction to 16');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('42646','0','3','0','2','0','100','0','0','30','0','0','84','3','0','0','0','0','0','1','0','0','0','0','0','0','0','When health between 20%-30%% (once) - Self: Talk 3 to invoker');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('42646','0','4','0','2','0','100','0','0','30','0','0','2','125','0','0','0','0','0','1','0','0','0','0','0','0','0','When health between 20%-30%% (once) - Self: Set faction to 125');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('42646','0','5','0','2','0','100','0','0','30','0','0','20','0','0','0','0','0','0','0','0','0','0','0','0','0','0','When health between 20%-30%% (once) - Self: Disable auto attack');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('42646','0','6','0','2','0','100','0','0','30','0','0','41','0','0','0','0','0','0','1','0','0','0','0','0','0','0','When health between 20%-30%% (once) - Self: Despawn instantly');
insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('42646','0','7','0','2','0','100','1','0','30','0','0','33','42893','0','0','0','0','0','17','0','10','0','0','0','0','0','Type a script description here.');

UPDATE `conditions` SET `ConditionValue1`=26361 WHERE `SourceEntry`=42644;

insert into `smart_scripts` (`entryorguid`, `source_type`, `id`, `link`, `event_type`, `event_phase_mask`, `event_chance`, `event_flags`, `event_param1`, `event_param2`, `event_param3`, `event_param4`, `action_type`, `action_param1`, `action_param2`, `action_param3`, `action_param4`, `action_param5`, `action_param6`, `target_type`, `target_param1`, `target_param2`, `target_param3`, `target_x`, `target_y`, `target_z`, `target_o`, `comment`) values('42777','0','11','0','52','0','100','0','4','42777','0','0','41','3000','0','0','0','0','0','1','0','0','0','0','0','0','0','Type a script description here.');

UPDATE `creature` SET `position_x`=3534.78 WHERE `guid`=86808;
UPDATE `creature` SET `position_y`=-6426.08 WHERE `guid`=86808;
UPDATE `creature` SET `position_z`=21.0333 WHERE `guid`=86808;
UPDATE `creature` SET `orientation`=3.24596 WHERE `guid`=86808;

REPLACE INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES (19, 0, 26388, 0, 0, 8, 0, 26372, 0, 0, 0, 0, 0, '');

