-- wow tokens
UPDATE `item_template` SET `name` = 'Olympus Coins - 01' , `description` = 'Ever since Saitamapaz fell mad, and went bald, he has been searching for every single one of his hairs around the world. You got a handful of them, will you dare to return it? (value: 01 Olympus Coins).' WHERE `entry` = '100601'; 
UPDATE `item_template` SET `name` = 'Olympus Coins - 02' , `description` = 'Ever since Saitamapaz fell mad, and went bald, he has been searching for every single one of his hairs around the world. You got a handful of them, will you dare to return it? (value: 02 Olympus Coins).' WHERE `entry` = '100602'; 
UPDATE `item_template` SET `name` = 'Olympus Coins - 05' , `description` = 'Ever since Saitamapaz fell mad, and went bald, he has been searching for every single one of his hairs around the world. You got a handful of them, will you dare to return it? (value: 05 Olympus Coins).' WHERE `entry` = '100603'; 
UPDATE `item_template` SET `name` = 'Olympus Coins - 10' , `description` = 'Ever since Saitamapaz fell mad, and went bald, he has been searching for every single one of his hairs around the world. You got a handful of them, will you dare to return it? (value: 10 Olympus Coins).' WHERE `entry` = '100604'; 

UPDATE `item_script_names` SET `ScriptName` = 'Olympus_coins_1' WHERE `Id` = '100601'; 
UPDATE `item_script_names` SET `ScriptName` = 'Olympus_coins_2' WHERE `Id` = '100602'; 
UPDATE `item_script_names` SET `ScriptName` = 'Olympus_coins_5' WHERE `Id` = '100603'; 
UPDATE `item_script_names` SET `ScriptName` = 'Olympus_coins_10' WHERE `Id` = '100604'; 

-- traduccion
UPDATE `locales_item` SET `name_loc6` = 'Olympus Coins - 01' , `name_loc7` = 'Olympus Coins - 01' , `description_loc6` = 'Desde que Saitamapaz cayó en la locura, y quedó calvo, ha estado buscando cada uno de sus pelos alrededor del mundo. Tú acabas de hacerte con un puñado de ellos, ¿te atreverás a devolverlos? (valor: 01 Olympus Coins)' , `description_loc7` = 'Desde que Saitamapaz cayó en la locura, y quedó calvo, ha estado buscando cada uno de sus pelos alrededor del mundo. Tú acabas de hacerte con un puñado de ellos, ¿te atreverás a devolverlos? (valor: 01 Olympus Coins)' WHERE `entry` = '100601'; 
UPDATE `locales_item` SET `name_loc6` = 'Olympus Coins - 02' , `name_loc7` = 'Olympus Coins - 02' , `description_loc6` = 'Desde que Saitamapaz cayó en la locura, y quedó calvo, ha estado buscando cada uno de sus pelos alrededor del mundo. Tú acabas de hacerte con un puñado de ellos, ¿te atreverás a devolverlos? (valor: 02 Olympus Coins)' , `description_loc7` = 'Desde que Saitamapaz cayó en la locura, y quedó calvo, ha estado buscando cada uno de sus pelos alrededor del mundo. Tú acabas de hacerte con un puñado de ellos, ¿te atreverás a devolverlos? (valor: 02 Olympus Coins)' WHERE `entry` = '100602'; 
UPDATE `locales_item` SET `name_loc6` = 'Olympus Coins - 05' , `name_loc7` = 'Olympus Coins - 05' , `description_loc6` = 'Desde que Saitamapaz cayó en la locura, y quedó calvo, ha estado buscando cada uno de sus pelos alrededor del mundo. Tú acabas de hacerte con un puñado de ellos, ¿te atreverás a devolverlos? (valor: 05 Olympus Coins)' , `description_loc7` = 'Desde que Saitamapaz cayó en la locura, y quedó calvo, ha estado buscando cada uno de sus pelos alrededor del mundo. Tú acabas de hacerte con un puñado de ellos, ¿te atreverás a devolverlos? (valor: 05 Olympus Coins)' WHERE `entry` = '100603'; 
UPDATE `locales_item` SET `name_loc6` = 'Olympus Coins - 10' , `name_loc7` = 'Olympus Coins - 10' , `description_loc6` = 'Desde que Saitamapaz cayó en la locura, y quedó calvo, ha estado buscando cada uno de sus pelos alrededor del mundo. Tú acabas de hacerte con un puñado de ellos, ¿te atreverás a devolverlos? (valor: 10 Olympus Coins)' , `description_loc7` = 'Desde que Saitamapaz cayó en la locura, y quedó calvo, ha estado buscando cada uno de sus pelos alrededor del mundo. Tú acabas de hacerte con un puñado de ellos, ¿te atreverás a devolverlos? (valor: 10 Olympus Coins)' WHERE `entry` = '100604'; 

